
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package arbolsintactico;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int uno = 2;
  public static final int error = 1;
  public static final int cero = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "uno",
  "cero"
  };
}

