
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package graficadoraa;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int rectangulo = 4;
  public static final int coma = 13;
  public static final int ovalo = 6;
  public static final int circulo = 5;
  public static final int color = 15;
  public static final int poligono = 9;
  public static final int estrella = 8;
  public static final int EOF = 0;
  public static final int cuadrado = 2;
  public static final int entero = 12;
  public static final int error = 1;
  public static final int tipo = 16;
  public static final int pComa = 14;
  public static final int linea = 3;
  public static final int parCierra = 11;
  public static final int parAbre = 10;
  public static final int trianguloRectangulo = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cuadrado",
  "linea",
  "rectangulo",
  "circulo",
  "ovalo",
  "trianguloRectangulo",
  "estrella",
  "poligono",
  "parAbre",
  "parCierra",
  "entero",
  "coma",
  "pComa",
  "color",
  "tipo"
  };
}

