
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package graficadoraa;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int coma = 6;
  public static final int EOF = 0;
  public static final int cuadrado = 2;
  public static final int entero = 5;
  public static final int rojo = 8;
  public static final int error = 1;
  public static final int rellena = 10;
  public static final int contorno = 11;
  public static final int pComa = 7;
  public static final int azul = 9;
  public static final int parCierra = 4;
  public static final int parAbre = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cuadrado",
  "parAbre",
  "parCierra",
  "entero",
  "coma",
  "pComa",
  "rojo",
  "azul",
  "rellena",
  "contorno"
  };
}

